"""esquema inicial

Revision ID: 6a534db3c066
Revises: 
Create Date: 2026-09-16 10:49:30.140624+00:00
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '6a534db3c066'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_profiles',
    sa.Column('scope', sa.String(length=64), nullable=False),
    sa.Column('agent_id', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('max_steps', sa.Integer(), nullable=False),
    sa.Column('prompt_version', sa.Integer(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('task_prompt', sa.Text(), nullable=False),
    sa.Column('versions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('scope', 'agent_id')
    )
    op.create_table('audit_entries',
    sa.Column('seq', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target', sa.String(length=128), nullable=False),
    sa.Column('detail', sa.Text(), server_default='', nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('seq'),
    sa.UniqueConstraint('hash')
    )
    op.create_index('ix_audit_at', 'audit_entries', [sa.literal_column('at DESC')], unique=False)
    op.create_index('ix_audit_target', 'audit_entries', ['target'], unique=False)
    op.create_table('requirements',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('owner', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('phi', sa.String(length=16), nullable=False),
    sa.Column('phi_set_by', sa.String(length=128), server_default='', nullable=False),
    sa.Column('title_enc', sa.LargeBinary(), nullable=False),
    sa.Column('description_enc', sa.LargeBinary(), nullable=False),
    sa.Column('acceptance_criteria_enc', sa.LargeBinary(), nullable=False),
    sa.Column('retention_until', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_requirements_created_at', 'requirements', [sa.literal_column('created_at DESC')], unique=False)
    op.create_table('attachments',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('requirement_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('added_by', sa.String(length=128), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name_enc', sa.LargeBinary(), nullable=False),
    sa.Column('detail_enc', sa.LargeBinary(), nullable=False),
    sa.Column('repo_enc', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_attachments_requirement', 'attachments', ['requirement_id'], unique=False)
    op.create_table('plans',
    sa.Column('requirement_id', sa.String(length=64), nullable=False),
    sa.Column('suggested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('overridden_by', sa.String(length=128), server_default='', nullable=False),
    sa.Column('items_enc', sa.LargeBinary(), nullable=False),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('requirement_id')
    )
    op.create_table('runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('requirement_id', sa.String(length=64), nullable=False),
    sa.Column('started_by', sa.String(length=128), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), server_default='', nullable=False),
    sa.Column('enabled_agents', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('profiles', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_runs_requirement_started', 'runs', ['requirement_id', sa.literal_column('started_at DESC')], unique=False)
    op.create_index('ix_runs_started_by', 'runs', ['started_by', sa.literal_column('started_at DESC')], unique=False)
    op.create_index('ix_runs_status', 'runs', ['status'], unique=False)
    op.create_table('llm_calls',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('agent_id', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('prompt_version', sa.Integer(), nullable=False),
    sa.Column('tokens_in', sa.Integer(), server_default='0', nullable=False),
    sa.Column('tokens_out', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=12, scale=6), server_default='0', nullable=False),
    sa.Column('duration_ms', sa.Integer(), server_default='0', nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='1', nullable=False),
    sa.Column('tools_used', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tools_rejected', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), server_default='', nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_llm_calls_at', 'llm_calls', [sa.literal_column('at DESC')], unique=False)
    op.create_index('ix_llm_calls_run', 'llm_calls', ['run_id'], unique=False)
    op.create_table('run_executions',
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('agent_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.Text(), server_default='', nullable=False),
    sa.Column('error', sa.Text(), server_default='', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tokens_in', sa.Integer(), server_default='0', nullable=False),
    sa.Column('tokens_out', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=12, scale=6), server_default='0', nullable=False),
    sa.Column('output_enc', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id', 'agent_id')
    )
    op.create_table('trace_events',
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('agent', sa.String(length=32), nullable=True),
    sa.Column('to_agent', sa.String(length=32), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('payload_enc', sa.LargeBinary(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id', 'seq')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trace_events')
    op.drop_table('run_executions')
    op.drop_index('ix_llm_calls_run', table_name='llm_calls')
    op.drop_index('ix_llm_calls_at', table_name='llm_calls')
    op.drop_table('llm_calls')
    op.drop_index('ix_runs_status', table_name='runs')
    op.drop_index('ix_runs_started_by', table_name='runs')
    op.drop_index('ix_runs_requirement_started', table_name='runs')
    op.drop_table('runs')
    op.drop_table('plans')
    op.drop_index('ix_attachments_requirement', table_name='attachments')
    op.drop_table('attachments')
    op.drop_index('ix_requirements_created_at', table_name='requirements')
    op.drop_table('requirements')
    op.drop_index('ix_audit_target', table_name='audit_entries')
    op.drop_index('ix_audit_at', table_name='audit_entries')
    op.drop_table('audit_entries')
    op.drop_table('agent_profiles')
    # ### end Alembic commands ###
