"""contador de identificadores

Revision ID: 888df80a11a2
Revises: 6a534db3c066
Create Date: 2026-09-16 11:03:24.201167+00:00
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '888df80a11a2'
down_revision = '6a534db3c066'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('id_counters',
    sa.Column('prefix', sa.String(length=16), nullable=False),
    sa.Column('value', sa.BigInteger(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('prefix')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('id_counters')
    # ### end Alembic commands ###
